
# MySQL数据源配置
DatabaseSettings:
  DatabaseURIL: "tcp(ruoyi-mysql:3306)"
  DatabaseURIR: "parseTime=True&loc=Local"
  DatabaseName: "chat_db" # 数据库名
  Username: "root"
  Password: "123456"

JwtSettings:
  SecretKey: "chat.com" #JWTkey

RedisName: "ruoyi-redis"

ServerName: "back-end"

